version: '3.3'

volumes:
  pg_data:
  static:

services:
  db:
    image: postgres:13
    env_file:
      - .env.example
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  backend:
    depends_on: 
      - db
    build: ./backend/
    env_file: .env.example
    volumes:
      - static:/backend_static
  
  nginx:
    depends_on:
      - backend
    build: ./nginx/
    env_file: .env.example
    volumes:
      - static:/staticfiles/
    ports:
      - 8000:80
