# Generated by Django 5.1.1 on 2024-09-27 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Меню')),
            ],
            options={
                'verbose_name': 'Меню',
                'verbose_name_plural': 'Меню',
            },
        ),
        migrations.CreateModel(
            name='SubMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Подменю')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu_page.menu')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu_page.submenu')),
            ],
        ),
    ]
