# Generated by Django 5.1.1 on 2024-09-27 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submenu',
            name='parent',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='menu_page.submenu'),
        ),
    ]
