# Generated by Django 5.1.1 on 2024-09-27 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_page', '0003_alter_submenu_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submenu',
            options={'verbose_name': 'Подменю', 'verbose_name_plural': 'Подменю'},
        ),
        migrations.AlterField(
            model_name='submenu',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Идентификатор URL', null=True, on_delete=django.db.models.deletion.CASCADE, to='menu_page.submenu'),
        ),
    ]
