# Generated by Django 5.1.1 on 2024-09-27 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_page', '0004_alter_submenu_options_alter_submenu_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='slug',
            field=models.SlugField(default=12, unique=True, verbose_name='Идентификатор'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submenu',
            name='slug',
            field=models.SlugField(default='asd', unique=True, verbose_name='Идентификатор'),
            preserve_default=False,
        ),
    ]
