# Generated by Django 5.1.1 on 2024-09-29 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_page', '0005_menu_slug_submenu_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='slug',
            field=models.SlugField(help_text='Идентификатор URL', unique=True, verbose_name='Идентификатор'),
        ),
        migrations.AlterField(
            model_name='submenu',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu_page.submenu'),
        ),
        migrations.AlterField(
            model_name='submenu',
            name='slug',
            field=models.SlugField(help_text='Идентификатор URL', unique=True, verbose_name='Идентификатор'),
        ),
    ]
