# Generated by Django 5.1.1 on 2024-09-29 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_page', '0006_alter_menu_slug_alter_submenu_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submenu',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submenus', to='menu_page.menu'),
        ),
        migrations.AlterField(
            model_name='submenu',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='menu_page.submenu'),
        ),
    ]
